query PrechecksStatusQuery($clusterUuid: UUID!) {
  prechecksStatus(clusterUuid: $clusterUuid) {
    endTime
    failureResults {
      precheckName
      cause
      remedy
      upgradeBlocker
      precheckIdentifier
      __typename
    }
    numPrechecks
    __typename
  }
}
