query AllPolarisReportConfigsQuery($polarisReportsFilters: [PolarisReportsFilterInput!]) {
  allRscReportConfigs(polarisReportsFilters: $polarisReportsFilters) {
    id
    name
    reportViewType
  }
}
