---
- name: Delete impacted companies from change record in ServiceNow
  hosts: localhost
  vars:
    servicenow_instance: "https://pepsicodev2.service-now.com"
    servicenow_user: "ITOPSBOT.INTEGRATION"
    servicenow_password: "44VaY3zF3bkd"
    change_sys_id: "b294fd4083cc9a5862e4c878beaad39a"
    companies: 
       - "76db5ca9db4b5780681064904b96197e"
       - "b6db5ca9db4b5780681064904b96197c"
  
  tasks:



    - name: Fetch impacted companies associated with change
      uri:
        url: "{{ servicenow_instance }}/api/now/table/u_m2m_companies_tasks?sysparm_query=u_task={{ change_sys_id }}&sysparm_fields=sys_id,u_company"
        method: GET
        user: "{{ servicenow_user }}"
        password: "{{ servicenow_password }}"
        return_content: yes
        status_code: 200
      register: res_com

    - name: Show fetched companies
      debug:
        var: res_com
    
    
    - name: Identify companies to delete
      set_fact:
        companies_to_delete: >-
          {{
            res_com.json.result | selectattr('u_company.value', 'defined') | selectattr('u_company.value', 'search', '^(?!' + companies | join('|') + ').*$') | list
          }}

    - name: Show companies to delete
      debug:
        msg: "{{ item.sys_id}}"
      with_items: "{{ companies_to_delete}}"

    - name: Delete impacted companies from change
      uri:
        url: "{{ servicenow_instance }}/api/now/table/u_m2m_companies_tasks/{{ item.sys_id }}"
        method: DELETE
        user: "{{ servicenow_user }}"
        password: "{{ servicenow_password }}"
        status_code: 204
      with_items: "{{ companies_to_delete}}"
      register: delete_results

    - name: Show delete results
      debug:
        var: delete_results

