---
- name: json data
  hosts: localhost
  gather_facts: no
  tasks:
      - name: Read file
        include_vars:
            file: jsonresult.json
            name: jsonData
      - name: finding the correct tageted version
        set_fact:
            progress: "{{item.node.progress}}"
            lastactivity: "{{item.node.lastActivityStatus}}"
        loop: "{{jsonData.data.activitySeriesConnection.edges}}"
      - name: Display variables using msg
        debug:
            msg:
                - "{{progress}}"
                - "{{lastactivity}}"

