- hosts: localhost
  gather_facts: no
  vars:
    access_token_uri: "https://hcl-pepsico-am.my.rubrik.com/api/client_token"
    client_id: "client|cc3f2839-63f2-4c66-8e03-211b66fa165e"
    client_secret: "U3AUwzR4UUimKN88TVmpO1RZBTmGH_O0_2FWFwajuoHYpTW71U5jQQvHY3T7P143"
    rsc_instance: "https://hcl-pepsico-am.my.rubrik.com"
    get_report_id_query: "getReportID.gql"
    duration_report_download_mutation: "downloadDurationReport.gql"
    duration_report_name: "Protection Tasks Details report(Will be used by HyperAutomation Team)"
    getReportExternalID_query: "getReportExternalID.gql"
    output_file: /home/ansible/script/duration_reporttttt.csv
    rsc:
      json:
        access_token: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL215LnJ1YnJpay5jb20vIiwiZXhwIjoxNzIzMTkwNzAxLCJpYXQiOjE3MjMxNDc1MDEsImlzcyI6Imh0dHBzOi8vbXkucnVicmlrLmNvbS8iLCJzdWIiOiJjbGllbnR8Y2MzZjI4MzktNjNmMi00YzY2LThlMDMtMjExYjY2ZmExNjVlIiwiaHR0cHM6Ly9teS5ydWJyaWsuY29tL2FjY291bnQiOiJoY2wtcGVwc2ljby1hbSIsImh0dHBzOi8vbXkucnVicmlrLmNvbS9vcmdhbml6YXRpb24iOiIxMzdhM2RiZS1jZTQ5LTRiZTAtYWNiNS1kNWUxNGVkMTUwY2MiLCJodHRwczovL215LnJ1YnJpay5jb20vY29ubmVjdGlvblR5cGUiOiJjbGllbnQiLCJodHRwczovL215LnJ1YnJpay5jb20vdXNlcm5hbWUiOiJoeXBlcmF1dG9tYXRpb24iLCJodHRwczovL215LnJ1YnJpay5jb20vc2Vzc2lvbklkIjoiYzYwYmUzZjUtNTk0Mi00MTg0LWFkZGItODFmNjA3YjA4MjQyIn0.LXWvtILgnUd4MqIOQXpeZFwYTSjNfAPUxsBhNlhmG6c0Qtws1yMX2prTedAv6X7M2XZJ7Regtb4H405eztMFU6yUxV5vT0HiVXmQE1YWTutRH9jyZReRBL0cxwlnXUeYy6mVoFOn-q9yHUHH25DKOsy_TWEhIyfzohFrddJ0QUZST7p8FegzeZ9iRwdFJ--xtVyDkjPfK8uKjrZKuVciOTANfUdQ-bh3lPgp45GXPiTdiqau2LQf-Q5zMw7UKwG2AawU7Oji_DQLl348G-CjVTqfIQ2Cctm__wS00k4C2onMIgn0Sx0peRYu3_016ySBtvDEpWczndG3nuZmqPpxmA"
    report_external_id: "4d2c0c53-4263-4adf-8258-8e2e28e0946f"


  tasks:
    - name: Download File
      get_url:
        url: "{{rsc_instance}}/file-downloads/{{report_external_id}}"
        dest: "{{output_file}}"
        headers:
          Authorization: "Bearer {{ rsc.json.access_token }}"
      register: download_file_result
    - debug:
        msg: "{{download_file_result}}"
