mutation PauseResumeClusterProtectionMutation($input: UpdateClusterPauseStatusInput!) {
  updateClusterPauseStatus(input: $input) {
    pauseStatuses {
      clusterUuid
      success
      __typename
    }
    __typename
  }
}


