- hosts: localhost
  gather_facts: no
  vars:
    pause_resume_protection_mutation: "resumePauseClusterProtection.gql"
    cluster_id: 08f6a160-e9f6-4698-a8bd-653a375fcad2
    client_id: "client|cc3f2839-63f2-4c66-8e03-211b66fa165e"
    client_secret: "U3AUwzR4UUimKN88TVmpO1RZBTmGH_O0_2FWFwajuoHYpTW71U5jQQvHY3T7P143"
    access_token_uri: "https://hcl-pepsico-am.my.rubrik.com/api/client_token"
    rsc_instance: "https://hcl-pepsico-am.my.rubrik.com"
    rsc:
      json:
        access_token: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL215LnJ1YnJpay5jb20vIiwiZXhwIjoxNzIzMzYyNDkxLCJpYXQiOjE3MjMzMTkyOTEsImlzcyI6Imh0dHBzOi8vbXkucnVicmlrLmNvbS8iLCJzdWIiOiJjbGllbnR8Y2MzZjI4MzktNjNmMi00YzY2LThlMDMtMjExYjY2ZmExNjVlIiwiaHR0cHM6Ly9teS5ydWJyaWsuY29tL2FjY291bnQiOiJoY2wtcGVwc2ljby1hbSIsImh0dHBzOi8vbXkucnVicmlrLmNvbS9vcmdhbml6YXRpb24iOiIxMzdhM2RiZS1jZTQ5LTRiZTAtYWNiNS1kNWUxNGVkMTUwY2MiLCJodHRwczovL215LnJ1YnJpay5jb20vY29ubmVjdGlvblR5cGUiOiJjbGllbnQiLCJodHRwczovL215LnJ1YnJpay5jb20vdXNlcm5hbWUiOiJoeXBlcmF1dG9tYXRpb24iLCJodHRwczovL215LnJ1YnJpay5jb20vc2Vzc2lvbklkIjoiN2VjNTg0MjAtNmQ2Yy00YzczLTgxY2QtYjliODkzZTYzZmFiIn0.QbqfuAwpTV7t8nnmpJ2iIH5fW8I59b7Q2VbVCP1TkKh_yqz51CiJDS2NUN2z5vNljlCZBUF2R4rjF_28lR8HiYYsn8Jba6TKnaBzofpmL4l2GXayh6ixDVj5H0Q4L2X2_6Rhf-G6RfCnskz_g44taL4DCYdEW75g7d6bGLEYZxOz4sjrBGhGB9KgpGC3I2wEPX3pKlBZ-kISAyHSPi5Ew-UnkhXVNKgBojzX_DJ5XKvnat308DCrnKidx8TIufXYz2LTidX-hQYdCHaq3OEndxi992fgugb0bW_uP-MxqCBNvwtaaIxzB6lON9cfPt0RNI_SidlbptVIFg9LGDEi8g"

  tasks:
    - block:
        - set_fact:
            resume_protection_rc: "success"
        - name: Connect to Rubrik
          uri:
            url: "{{ access_token_uri }}"
            method: POST
            body_format: json
            body:
              client_id: "{{ client_id }}"
              client_secret: "{{ client_secret }}"
          register: rsc

        - name: RSC GraphQL Mutation || Resume Protection and backup
          uri:
            url: "{{ rsc_instance }}/api/graphql"
            method: POST
            headers:
              content-type: "application/json"
              authorization: "Bearer {{ rsc.json.access_token }}"
            body_format: json
            body:
              query: '{{ lookup("file", "{{ pause_resume_protection_mutation }}") }}'
              variables: |
                {
                  "input": {
                    "clusterUuids": [
                      "{{cluster_id}}"
                    ],
                    "togglePauseStatus": false
                  }
                }
          register: resume_protection_status

        - set_fact:
            resume_protection_rc: "failed"
          when: resume_protection_status.json.errors is defined
        - debug:
            msg: "Resume Protection Successfull"
          when: resume_protection_status.json.errors is not defined

      rescue:
        - set_fact:
            resume_protection_rc: "failed"
      always:
        - debug:
            msg: "error"
          when: resume_protection_rc is defined and resume_protection_rc == "failed"
